image: Visual Studio 2017

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017"
    QTDIR: C:\Qt\5.13.0\msvc2017_64
    
    
clone_depth: 1

init:
  - set TAG_NAME=%appveyor_build_version%
  - set QTDIR=C:\Qt\5.13.0\msvc2017_64
  - set PATH=C:\Qt\5.13.0\msvc2017_64\bin;%PATH%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

build_script:
  - call "scripts/build_windows.cmd"

artifacts:
  - path: build_x64\Release\bin\win32\SupraFit_nightly_$(appveyor_build_version)_x64_windows.zip
    name: SupraFit_x64

  - path: build_x32\Release\bin\win32\SupraFit_nightly_$(appveyor_build_version)_x32_windows.zip
    name: SupraFit_x32



deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: $(appveyor_build_version)
  description: $(appveyor_build_version)
  auth_token:
    secure: lNrwOGAylXafSwJAAwEbYBFGbpGjy7aYSCyAWl9jikP22ykJ1BqwKPKhKjo+f1JT
  prerelease: true
  draft: true
  artifact: SupraFit_x64,SupraFit_x32
  skip_tags: true
  force_update: true

