image: Visual Studio 2017

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017"
    QTDIR: C:\Qt\5.12.2\msvc2017_64
    
    
clone_depth: 1

init:
  - set TAG_NAME=%appveyor_build_version%
  - set QTDIR=C:\Qt\5.12.2\msvc2017_64
  - set PATH=C:\Qt\5.12.2\msvc2017_64\bin;%PATH%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

build_script:
  - call "scripts/build_windows.cmd"

artifacts:
  - path: build\Release\SupraFit_nightly_$(appveyor_build_version)_windows.zip
    name: portable


deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: $(appveyor_build_version)
  description: $(appveyor_build_version)
  auth_token:
    secure: lNrwOGAylXafSwJAAwEbYBFGbpGjy7aYSCyAWl9jikP22ykJ1BqwKPKhKjo+f1JT
  prerelease: true
  artifact: portable
