#!/bin/bash
set -ex

cp misc/SupraFit.desktop release/bin/linux/
cp misc/SupraFit.png release/bin/linux/
cd release/bin/

wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
chmod a+x linuxdeployqt-continuous-x86_64.AppImage

cd linux

mkdir -p lib

mkdir -p plugins

cd plugins

cp -r  $(find $HOME -name '*libqxcb-glx-integration*' -print 2>/dev/null |head -n1 |sed 's/xcbglintegrations\/libqxcb-glx-integration.so/iconengines/g') .
cp -r  $(find $HOME -name '*libqxcb-glx-integration*' -print 2>/dev/null |head -n1 |sed 's/xcbglintegrations\/libqxcb-glx-integration.so/imageformats/g') .
cp -r  $(find $HOME -name '*libqxcb-glx-integration*' -print 2>/dev/null |head -n1 |sed 's/xcbglintegrations\/libqxcb-glx-integration.so/platforms/g') .
cp -r  $(find $HOME -name '*libqxcb-glx-integration*' -print 2>/dev/null |head -n1 |sed 's/xcbglintegrations\/libqxcb-glx-integration.so/platforminputcontexts/g') .
cp -r  $(find $HOME -name '*libqxcb-glx-integration*' -print 2>/dev/null |head -n1 |sed 's/xcbglintegrations\/libqxcb-glx-integration.so/xcbglintegrations/g') .
find . -name '*wayland*' -delete
cd ..

cat <<ab>qt.conf
# Generated by linuxdeployqt
# https://github.com/probonopd/linuxdeployqt/
[Paths]
Prefix = ./
Plugins = plugins
Imports = qml
Qml2Imports = qml
ab

mkdir -p usr/share/doc/libc6/
touch usr/share/doc/libc6/copyright
../linuxdeployqt-continuous-x86_64.AppImage SupraFit.desktop -unsupported-allow-new-glibc -verbose=1 -appimage || true 

cp SupraFit*.AppImage SupraFit-nightly-x86_64.AppImage
