name: AutomaticBuild

on: [push]

jobs:
  linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Update Modules and Build
      run: sh scripts/build_unix.sh
        
  windows:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Update Modules and Build
      run: scripts/build_windows.bat
    - uses: actions/upload-artifact@v1
      with:
        name: QBit
        path: build_x64\bin\win32\Release\SupraFit_latest_x64_windows.zip
