name: AutomaticBuild

on:
  push:
    branches: [ master ] #Everytime master branch is updated
    paths: ['.github/workflows/*',  'src/*'] #only when these files are modifed
  pull_request:
    branches: [ master ] #for every pull request going to master
    paths: ['.github/workflows/*', 'src/*'] #only when these files are modifed

jobs:
  linux:
    runs-on: ubuntu-16.04
    
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtcharts
          version: 5.15.1

      - name: Update Modules and Build
        run: sh scripts/build_unix_github.sh

      - name: Install more libs
        run: sudo apt-get install -y libxcb-icccm4 libxcb*

      - name: Deploy
        run: sh scripts/deploy_unix.sh 
      
      - uses: actions/upload-artifact@v1
        with:
          name: SupraFit_Linux
          path: ./release/bin/linux/SupraFit-nightly-x86_64.AppImage
        
  windows:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtcharts
          version: 5.15.1
      - name: Update Modules and Build
        run: scripts/build_windows_x64.bat
      - uses: actions/upload-artifact@v1
        with:
          name: SupraFit_Windows
          path: build_x64\bin\win32\Release\SupraFit_latest_x64_windows.zip

  publish:
    needs: [linux, windows]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artefacts
        uses: actions/download-artifact@v2
        with:
          path: artefacts
      
      - name: Printout
        run: ls -R ./artefacts 
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 2.5.${{ github.run_number  }}
          release_name: Nightly 2.5.${{ github.run_number }}
          draft: true
          prerelease: true

      - name: Upload Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artefacts/SupraFit_Linux/SupraFit-nightly-x86_64.AppImage
          asset_name: Linux
          asset_content_type: application/zip
      
      - name: Upload Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: artefacts/SupraFit_Windows/SupraFit_latest_x64_windows.zip
           asset_name: Windows
           asset_content_type: application/zip
